Repository umijs/umi-server, pull requests merged in 2019-11, with the labels that each got.

#20 fix: locale umi when target use node
  examples/eggjs/app/web/pages/home/index.jsx
  examples/eggjs/package.json
  examples/normal/src/assets/yay.jpg
  examples/normal/src/pages/index.css
Labels: bug

#21 feat: better render perfs, filter root Container parse
  packages/umi-server/src/index.ts
  packages/umi-server/src/utils.ts
  packages/umi-server/test/__snapshots__/utils.test.ts.snap
  packages/umi-server/test/fixtures/ssr-multiply-data/.umirc.js
  packages/umi-server/test/fixtures/ssr-multiply-data/__snapshots__/index.test.ts.snap
  packages/umi-server/test/fixtures/ssr-multiply-data/index.test.ts
  packages/umi-server/test/fixtures/ssr-multiply-data/pacakge.json
  packages/umi-server/test/fixtures/ssr-multiply-data/pages/data.json
  packages/umi-server/test/fixtures/ssr-multiply-data/pages/index.js
  packages/umi-server/test/fixtures/ssr-multiply-data/pages/index.module.less
  packages/umi-server/test/fixtures/ssr/__snapshots__/index.test.ts.snap
  packages/umi-server/test/fixtures/ssr/index.test.ts
  packages/umi-server/test/utils.test.ts
Labels: enhancement

#27 fix: match publicPath regexp
  packages/umi-server/src/utils.ts
  packages/umi-server/test/__snapshots__/utils.test.ts.snap
  packages/umi-server/test/utils.test.ts
Labels: bug

#29 feat: dev env clear cache, not suggest polyfill
  examples/ant-motion/server.js
  examples/eggjs/app/controller/home.js
  examples/eggjs/app/web/app.js
  examples/eggjs/app/web/utils/isBrowser.ts
  examples/eggjs/app/web/utils/request.ts
  examples/koajs/server.js
  package.json
  packages/umi-plugin-prerender/test/fixtures/normal-static-markup/__snapshots__/index.test.ts.snap
  packages/umi-plugin-prerender/test/fixtures/normal/__snapshots__/index.test.ts.snap
  packages/umi-plugin-prerender/test/fixtures/react-document-title/__snapshots__/index.test.ts.snap
  packages/umi-plugin-prerender/test/fixtures/react-helmet/__snapshots__/index.test.ts.snap
  packages/umi-server/README.md
  packages/umi-server/src/index.ts
  packages/umi-server/test/__snapshots__/utils.test.ts.snap
  packages/umi-server/test/fixtures/ssr-dynamicImport/__snapshots__/index.test.ts.snap
  packages/umi-server/test/fixtures/ssr/__snapshots__/index.test.ts.snap
  packages/umi-server/test/utils.test.ts
Labels: enhancement

#30 feat: isBrowser util
  examples/eggjs/app/web/app.js
  examples/eggjs/app/web/utils/request.ts
  packages/umi-server/README.md
  packages/umi-server/src/isBrowser.ts
Labels: enhancement

#36 fix: return undefined when page not found
  packages/umi-server/src/index.ts
  packages/umi-server/test/fixtures/ssr/index.test.ts
Labels: bug

#37 🐛 fix: eggjs example params might be undefined
  examples/eggjs/app/web/utils/request.ts
Labels: chore

#38 fix: history object oom
  examples/ant-motion/package.json
  examples/koajs/package.json
  examples/normal/package.json
  package.json
Labels: bug

#43 upd: rc-queue-anim for ssr support
  examples/ant-motion/package.json
Labels: enhancement

#45 fix: eggjs demo dva always return all model
  examples/eggjs/app/web/models/home.ts
  examples/eggjs/app/web/pages/home/index.jsx
  examples/eggjs/app/web/pages/news/$id.tsx
Labels: bug

#46 fix: koajs model demo
  examples/expressjs/src/pages/count.js
  examples/expressjs/src/pages/index.js
  examples/koajs/src/pages/count.js
  examples/koajs/src/pages/users.js
Labels: chore

#47 fix: polyfill global.location
  .github/workflows/ci.yml
  .gitignore
  circle.yml
  package.json
  packages/umi-server/src/index.ts
  packages/umi-server/src/utils.ts
  packages/umi-server/test/polyfill.test.ts
  scripts/startBuild.js
Labels: bug
